---
collections:
## CERTIFIED ##
- kubernetes.core
#  - name: ansible.controller
#    version: 4.6.16
  #version: 4.6.8
#  - name: ansible.posix
#    version: ">=1,<2"  
#- infoblox.nios_modules
#- vyos.vyos
#- ansible.windows
#- arista.eos
#- name: azure.azcollection
#  version: 1.14.0


## VALIDATED ##
#- infra.aap_configuration
#  version: 3.1.0

## COMMUNITY ##
#  - name: community.general
#    version: 8.5.0
#- name: vmware.vmware_rest
#  version: 2.3.1
#- name: community.vmware
#  version: 2.4.0
#- awx.awx
#- oracle.oci
