#---
#collections:
## CERTIFIED ##
#- kubernetes.core
#- community.kubernetes
#  - name: ansible.controller
#    version: 4.6.16
  #version: 4.6.8
#  - name: ansible.posix
#    version: ">=1,<2"  
#- infoblox.nios_modules
#- vyos.vyos
#- ansible.windows
#- arista.eos
#- name: azure.azcollection
#  version: 1.14.0


## VALIDATED ##
#- name: infra.aap_configuration
#  version: 4.2.0

## COMMUNITY ##
#  - name: community.general
#    version: 8.5.0
#- name: vmware.vmware_rest
#  version: 2.3.1
#- name: community.vmware
#  version: 2.4.0
#- awx.awx
#- oracle.oci
#- name: ansible.platform
#- name: ansible.hub
#- name: ansible.controller
#  version: ">=4.6.0"
#- name: ansible.eda
#- name: infra.aap_configuration
#  version: 3.9.1
