---
collections:

## CERTIFIED ##
#- frr.frr
- name: ansible.controller
  version: 4.5.15
  #version: 4.6.3
  #version: 4.4.8
#- infoblox.nios_modules
#- vyos.vyos
#- ansible.windows
#- arista.eos
#- name: azure.azcollection
#  version: 1.14.0


## VALIDATED ##
#- infra.ah_configuration

## COMMUNITY ##
- name: community.general
  version: 8.5.0
#- name: vmware.vmware_rest
#  version: 2.3.1
#- name: community.vmware
#  version: 2.4.0
#- awx.awx
#- oracle.oci
