---
collections:


## CERTIFIED ##
#- frr.frr
#- ansible.controller
#- infoblox.nios_modules
#- vyos.vyos
#- ansible.windows
#- arista.eos
#- name: azure.azcollection
#  version: 1.14.0


## VALIDATED ##
#- infra.ah_configuration


## COMMUNITY ##
#- name: community.general
#  version: 6.2.0
#- name: vmware.vmware_rest
#  version: 2.3.1
- name: community.vmware
  version: 2.4.0
#- awx.awx
#- oracle.oci



