---
- name: 'Log in  (obtain access token)'
  redhat.openshift.openshift_auth:
    username: "{{ k8s_username }}"
    password: "{{ k8s_password }}"
  register: openshift_auth_results

#- name: "set fact"
#  set_fact:
#    k8s_api_key: "{{ openshift_auth_results.k8s_auth.api_key }}"
