- name: Hello World Sample
  hosts: all
  gather_facts: False
  tasks:   
    - name: Say Hello
      debug:
        msg: "Hello World!"
    
    - name: download file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/jbird2021/ansible-tower-samples/master/README.md
        dest: /tmp/readme.md
