- name: Hello World Sample
  hosts: all
  gather_facts: False
  tasks:   
    - name: Say Hello
      debug:
        msg: "Hello World!"
    - name: Induce an exception to see what happens
      ansible.builtin.ping:
        data: crash
