- name: win_powershell.yml
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
        script: |
          echo "Hello World"
