- name: role_team_assignment.yml
  hosts: localhost
  gather_facts: false
      
  tasks:
    - name: role_team_assignment
      ansible.controller.role_team_assignment:
        controller_host: "{{ host }}"
        controller_username: "{{ username }}"
        controller_password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        role_definition: Organization Execute
        object_id: 2
        team: Team1
        state: present
