- name: Content creation started
  hosts: localhost
  gather_facts: false
  vars:
    controller_host: "https://10.0.108.52"
#    controller_username: "admin"
#    controller_password: "test" 
#    controller_password: !vault |
#          $ANSIBLE_VAULT;1.1;AES256
#          66346161326266386336316630663663363737346462633434636234653964326639663563626339
#          6261383737653662363431363062386165343939333264650a633038303962623337313365373362
#          37653832393431343234323933343037376239376665336166313662373462393235323337353331
#          6163336264333031650a313936373236343735366163373939396565356530376639613030396333
#          37313439613533383063393433356233626161366334623236303564613437343265
          
  tasks:

 #   - name: Create temporary inventory file
 #     ansible.controller.inventory:
 #       name: "TestInventory"
 #       organization: "Default"
 #       state: present
 #       controller_host: "{{ controller_host }}"
 #       controller_username: "{{ controller_username }}"
 #       controller_password: "{{ controller_password }}"
 #       validate_certs: false
        
 #   - name: Delete temporary inventory file
 #     ansible.controller.inventory:
 #       name: "TestInventory"
 #       organization: "Default"
 #       state: absent
 #       controller_host: "{{ controller_host }}"
 #       controller_username: "{{ controller_username }}"
 #       controller_password: "{{ controller_password }}"
 #       validate_certs: false

    - name: Triggering workflow job template
      ansible.controller.workflow_launch:
        name: "Biztalk_NonProd_Template"
        controller_host: "{{ controller_host }}"
        controller_username: "{{ lookup ('env', 'TOWER_USERNAME') }}"
        controller_password: "{{ lookup ('env', 'TOWER_PASSWORD') }}"
        validate_certs: false
