---
- name: Testing ansible.controller.export
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Export Assets
      ansible.controller.export:
        projects: 'all'
        controller_host: 10.0.109.3
        controller_username: admin
        controller_password: test
        validate_certs: False
      register: export_output

    - name: Show Export Output.
      ansible.builtin.debug:
        var: export_output  
