- name: Content creation started
  hosts: localhost
  gather_facts: false

  vars:
    host: "https://10.0.111.201/"
    username: "admin"
    password: "test" 

  tasks:
    - name: Create a workflow job template
      ansible.controller.workflow_job_template:
        name: example-workflow
        description: created by Ansible Playbook
        organization: Default
        controller_host: "{{ host }}"
        controller_username: "{{ username }}"
        controller_password: "{{ password }}"
        validate_certs: false

    
    - name: Create a node, follows workflow_job_template example
      ansible.controller.workflow_job_template_node:
        identifier: my-first-node
        workflow: example-workflow
        unified_job_template: job1
        organization: Default
        controller_host: "{{ host }}"
        controller_username: "{{ username }}"
        controller_password: "{{ password }}"
        validate_certs: false



