- name: Content creation started
  hosts: localhost
  vars:
    controller_host: "https://10.0.109.163/"
    controller_username: "admin"      #username and password changed
    controller_password: "test"       #username and password changed
  gather_facts: false

  tasks:
    - name: Create temporary inventory file
      ansible.controller.inventory:
        name: "TestInventory"
        organization: Default
        state: present
    
    
    
    
    
    
#    - name: Include variables from respective files
#      include_vars:
#        file: credentials.yml
#
#    - name: Debug loaded variables
#      debug:
#        var: creds###
#
#    - name: Debug loaded variables
#      debug:
#        var: orgs
#
#    - name: Add credentials to controller
#      ansible.controller.credential:
#        controller_host: "{{ controller_host }}"
#        controller_username: "{{ controller_username }}"
#        controller_password: "{{ controller_password }}"
#        name: "{{ item.name }}"
#        organization: "{{ item.org }}"
#        description: "Added by Gokulan"
#        credential_type: "{{ item.type }}"
#        state: "{{ item.state }}"
#        inputs:
#          password: "{{ item.password }}"
#          username: "{{ item.username }}"
#        validate_certs: false
#      loop: "{{ creds }}"
#
#    - name: Add organization to the controller
#      ansible.controller.organization:
#        controller_host: "{{ controller_host }}"
#        controller_username: "{{ controller_username }}"
#        controller_password: "{{ controller_password }}"
#        name: "{{ item.name }}"
#        description: "{{ item.description }}"
#        state: "{{ item.state }}"
#        validate_certs: false
#      loop: "{{ orgs }}"
