- name: Content creation started
  hosts: localhost
  gather_facts: false
  vars:
    host: "https://10.0.108.52"
    username: "admin"
    password: "test" 
#    controller_password: !vault |
#          $ANSIBLE_VAULT;1.1;AES256
#          66346161326266386336316630663663363737346462633434636234653964326639663563626339
#          6261383737653662363431363062386165343939333264650a633038303962623337313365373362
#          37653832393431343234323933343037376239376665336166313662373462393235323337353331
#          6163336264333031650a313936373236343735366163373939396565356530376639613030396333
#          37313439613533383063393433356233626161366334623236303564613437343265
          
  tasks:
 #   - name: Assign project permissions from Organzaition2 to Team1 
 #     ansible.controller.role:
 #       team: Team1
 #       project: Project1
 #       role: use
 #       lookup_organization: Organization1
 #       controller_host: "{{ host }}"
 #       controller_username: "{{ username }}"
 #       controller_password: "{{ password }}"
 #       validate_certs: false
        
    - name: Create temporary inventory file
      ansible.controller.inventory:
        name: "TestInventory"
        organization: "Default"
        state: present
        controller_host: "{{ host }}"
        controller_username: "{{ username }}"
        controller_password: "{{ password }}"
        validate_certs: false
        
    - name: Delete temporary inventory file
      ansible.controller.inventory:
        name: "TestInventory"
        organization: "Default"
        state: absent
        controller_host: "{{ host }}"
        controller_username: "{{ username }}"
        controller_password: "{{ password }}"
        validate_certs: false

#    - name: Triggering workflow job template
#      ansible.controller.workflow_launch:
#        name: "NonProd_Template"
#        controller_host: "{{ controller_host }}"
#        controller_username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
#        controller_password: '{{ lookup("env", "CONTROLLER_PASSWORD") }}'
#        validate_certs: false
