- name: Content creation started
  hosts: localhost
  gather_facts: false
  vars:
    controller_host: "10.0.108.52"
    controller_username: "admin333"
    #controller_password: "test" 
    controller_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31336263613861623763366562613563613234633966636362383631346135333534383435396330
          3463616532306535323031663637393731336362323731630a386466363364386231663139623132
          36613165633338656436663932666363313332623763636638643536306331646632643731383832
          3466643362306234640a633266343638383232633938306438333563623737346136383039373230
          6431
          
  tasks:

    - name: Create temporary inventory file
      ansible.controller.inventory:
        name: "TestInventory"
        organization: "Default"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: false
        
    - name: Delete temporary inventory file
      ansible.controller.inventory:
        name: "TestInventory"
        organization: "Default"
        state: absent
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: false
