#---
#- name: Testing ansible.controller.export
#  hosts: localhost
#  gather_facts: false
#
#  tasks:
#    - name: Export Assets
#      ansible.controller.export:
#        job_templates: "all"
#        controller_host: 10.0.109.3
#        controller_username: admin
#        controller_password: test
#        validate_certs: False
#      register: export_output
#    - name: Show Export Output.
#      ansible.builtin.debug:
#        var: export_output  
---
- name: export stuff using ansible.controller collection
  hosts: all
  collections:
    - ansible.controller
  tasks:
    - name: export it
      export:
        controller_host: https://10.0.109.60
        controller_username: "admin"
        controller_password: "test"
        validate_certs: false
#        inventory: 'SinglehostInv'
        credential_types: all
      register: controller_list

    - name: debug output
      debug:
        var: controller_list.assets
