- name: Content creation started
  hosts: localhost
  gather_facts: false
  vars:
    controller_host: "10.0.108.52"
    controller_username: "admin333"
    #controller_password: "test" 
    controller_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64386631326462616332613263353233663364313438396637633931353061316666376132346137
          6264333330323534366139663530396538333934366538350a613835613230326435373832376466
          31363164313630636333373566373331613362646531323937353138663566333132353330373762
          6239653366646365640a366535663233356333613231613461623365306336613364323161353431
          3938
          
  tasks:

    - name: Create temporary inventory file
      ansible.controller.inventory:
        name: "TestInventory"
        organization: "Default"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: false
        
    - name: Delete temporary inventory file
      ansible.controller.inventory:
        name: "TestInventory"
        organization: "Default"
        state: absent
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: false
