---
- name: Testing awx.awx.export
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Export Assets
      awx.awx.export: 
        all: True
        #job_templates: "Demo Job Template"
        #inventory: ['Demo Inventory']
        #assets: "{{ lookup( 'ansible.builtin.file', './awx_test_export.json' ) | from_json() }}"
        controller_host: 10.0.110.31
        controller_username: admin
        controller_password: test
        validate_certs: False
      register: export_output

    - name: Show Export Output.
      ansible.builtin.debug:
        var: export_output  
