- name: base64test.yml
  hosts: localhost
  gather_facts: False
  become: False
  
  tasks:   
    - ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', 'test.cert') }}"

    - ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', 'test.cert') | b64encode }}"

    - ansible.builtin.debug:
        msg: "{{ (lookup('ansible.builtin.file', 'test.cert') | b64encode) b64decode }}"        
