- name: base64test.yml
  hosts: localhost
  gather_facts: False
  become: False
  
  tasks:   
    - name: do the encode
      shell: echo {{ lookup('ansible.builtin.file', 'test.cert') }} > /tmp/output
      

    - ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', '/tmp/output') }}"

    - ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', 'test.cert') | b64encode }}"




    - ansible.builtin.debug:
        msg: "{{ (lookup('ansible.builtin.file', 'test.cert') | b64encode) | b64decode }}"        
