---
- hosts: all
  gather_facts: true
  vars:
    sleep_interval: 1
    num_messages: 60
  tasks:
    - name: debug and sleep for configured time
      include_tasks: debug_and_sleep.yml
      vars:
        message_number: "{{ item }}"
      loop: "{{ range(0, num_messages|int)|list }}"
