---
- name: Connect to Cisco Switch
  hosts: all
  gather_facts: no
  tasks:
    - name: Run show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: output
    - name: Print output
      debug:
        var: output.stdout_lines
