---
- name: Test command module running on localhost
  hosts: localhost
  gather_facts: no
  become: false

  tasks:
    - name: Perform a cat
      ansible.builtin.command: cat /usr/bin/dig/text.txt
      register: cmd_out1
      check_mode: no
    - name: Perform DNS lookup of FQDN
      ansible.builtin.command: /usr/bin/dig {{ g_vm_fqdn }} +short +noedns
      register: cmd_out
      check_mode: no
