- name: copy_from_to_tmp.yml
  hosts: localhost
  #become: true
  vars:
    folder_tower: "/tmp/controler/"
    folder_node: "/tmp/node/"

  tasks:
    - name: "1.1 - :: Display folder TOWER:/tmp/controler/"
      shell: |
        echo "--------------------------------------------------------------------------------"
        echo " HOSTNAME     : $(hostname)"
        echo " folder_tower : {{ folder_tower }}"
        echo " folder_node  : {{ folder_node }}"
        echo "---{{ folder_tower }}-----------------------------------------------------------"
        ls -ltr "{{ folder_tower }}"  2>&1
        echo "--------------------------------------------------------------------------------"
      # delegate_to: "{{ varTOWER | lower}}"    


    - name: "1.2 - :: Copy folder from 'TOWER:{{ folder_tower }}' to 'NODE:{{ folder_node }}' "
      copy:
        src: "{{ folder_tower }}"
        dest: "{{ folder_node }}"

    - name: Write TADDM to a file
      ansible.builtin.copy:
        content: "Just some test content"
        dest: /tmp/test.txt
