- name: test create user
  hosts: all

  tasks:
  - name: Ensure group exists
    ansible.builtin.group:
      name: "{{ my_group }}" 
      state: present
  
  - name: create user
    ansible.builtin.user: 
      name: "{{ my_user }}"
      groups: "{{ my_group }}" 
      #password: "{{ my_pass | password_hash('sha512') }}"
      password_expire_max: 60
      password_expire_min: 30
      password_expire_warn: 10


  - name: Remove the user
    ansible.builtin.user:
      name: "{{ my_user }}"
      state: absent
      remove: yes
    when: "{{ remove_user }}"
