- name: test create user
  hosts: all
  serial: 1
  order: sorted
  tasks:
  - name: create user
    user: name={{ my_user }} groups={{ my_group }} password="{{ my_pass | password_hash('sha512') }}"
    
