- name: create_local_directory.yml
  hosts: localhost
  vars:
    base_directory: staging
    create_directory: demo_project
    
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "/{{base_directory}}/{{create_directory}}"
        state: directory
        mode: '0755'

    - name: Create a directory if it does not exist
      file:
        path: "/{{base_directory}}/{{create_directory}}"
        state: directory
        mode: '0755'
