- name: create_jobtemplate_with_survey.yml
  hosts: localhost
  #gather_facts: True
  #become: True
  tasks:   
    - name: Create Ping job template
      job_template:
        controller_host: "10.0.109.2"
        controller_username: "admin"
        controller_password: "test"
        name: "create_jobtemplate_with_survey"
        job_type: "run"
        organization: "Default"
        inventory: "Demo Inventory"
        project: "Demo Project"
        playbook: "hello_world.yml"
        state: "present"
        survey_enabled: yes
        survey_spec: "{{ lookup('file', 'my_survey.json') }}"
