- name: Hello World Sample
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    my_var: "Yes"
    
  
  tasks:   
    - name: Output text
      debug:
        msg: "{{ my_var }}"
    - name: Output bool
      debug:
        msg: "{{ my_var | bool}}"     
