---
- name: delegate_to.yml
  hosts: all
  tasks:
  - name: "Execution node: {{ awx_execution_node }}; Managed Node: {{ ansible_hostname }} var foo={{ foo.lolo }}"
      shell: "echo Hello World"
    delegate_to: "{{ awx_execution_node }}"
