---
- name: Hello World!
  hosts: all
  vars:
    foo: 
      lolo: lele 
  tasks:
 
  - name: Check SSH
    shell: "echo Hello World"

  - name: Hello World!
    debug: 
      msg: "Execution node: {{ awx_execution_node }}; Managed Node: {{ ansible_hostname }} var foo={{ foo.lolo }}"
    delegate_to: "{{ awx_execution_node }}"
