- name: dnf_java.yml
  hosts: all
  gather_facts: False
  become: True
  tasks:   
    - name: Package state=present
      ansible.builtin.package:
        state: present
        name:
          - java-1.8.0-openjdk 
