- hosts: all
  become: true
  
  tasks:
    - name: "Gather package facts"
      package_facts:
        manager: auto
 
    - name: "Print installed package versions"
      debug:
        msg: |
          {{ item }}
          Version: {{ ansible_facts.packages[item][0]['version'] }}
          Release: {{ ansible_facts.packages[item][0]['release'] }}
          
   #   loop: "{{ ansible_facts.packages.keys() | select('match','^falcon-sensor$') | list }}"
   #   when: "'falcon-sensor' in ansible_facts.packages"
      loop: "{{ ansible_facts.packages.keys() | list }}"
     # when: "'powershell' in ansible_facts.packages"      

