- name: job_launch.yml
  hosts: all
  #gather_facts: True
  #become: True
  tasks:   
    - name: Launch a job
      ansible.controller.job_launch:
        job_template: "Demo Job Template"
      register: job
