- name: kubernetes_core.yml
  hosts: all
  gather_facts: False
  become: False
  tasks:   
  - name: Create a k8s namespace
    kubernetes.core.k8s:
      name: testing
      api_version: v1
      kind: Namespace
      state: present
