- hosts: localhost
    
  gather_facts: no
  vars:
    num_loops: 10
    delay_secs: 30
  tasks:
    - name: print items
      debug: "{{ index_var }}"
      until: num_loops = index_var
      retries: num_loops
     

