- hosts: localhost
  collections: 
    - community.general
  gather_facts: no
  vars:
    echo_list:
      - "one"
      - "two"
      - "three"
  tasks:
    - name: print items
      debug: 
        msg:
          - "{{ item }}"
      loop: "{{ echo_list }}"
      
    - name: register echo
      shell: | 
        echo "{{ item }}"
      loop: "{{ echo_list }}"
      register: shell_echo 

    - name: Setting booleans using complex argument style
      ansible.builtin.set_fact:
        one_fact: yes
        other_fact: no
    - name: Add label to organization
      label:
        name: Custom Label
        organization: Default
