- hosts: localhost
  collections: 
    - community.general
  gather_facts: no
  vars:
    echo_list:
      - "one"
      - "two"
      - "three"
  tasks:
    - name: print items
      debug: 
        msg:
          - "{{ item }}"
      loop: "{{ echo_list }}"
      
    - name: register echo
      shell: | 
        echo "{{ item }}"
      loop: "{{ echo_list }}"
      register: shell_echo 
  
    - name: print items as json
      debug:
        msg: 
          - "{{ shell_echo  | json_query('results[*].stdout') }}"
    - name: Echo my_env_var
      shell: "echo $MY_ENV_VARIABLE"
      environment:
        MY_ENV_VARIABLE: whatever_value

    - name: Echo my_env_var again
      shell: "echo $MY_ENV_VARIABLE"
