---

- name: Migrate Networking Inventory....
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
#  vars_files:
#    - /vaults/tower.yml

  tasks:
    #   - name: Add inventory
    #  awx.awx.inventory:
    #    controller_host: 10.0.109.3
    #    controller_username: "admin"
    #    controller_password: "test"
    #    validate_certs: False
    #    name: "Foo Inventory"
    #    description: "Our Foo Cloud Servers"
    #    organization: "Default"
    #    state: present
       
    - name: Export inventory
      ansible.controller.export:
        inventory: 'inventory_test2'
        controller_host: 10.0.109.3
        controller_username: "admin"
        controller_password: "test"
        validate_certs: False
      register: export_output

    - name: Import inventory
      ansible.controller.import:
        assets: "{{ export_output.assets }}"
        controller_host: 10.0.110.51
        controller_username: "admin"
        controller_password: "test"
        validate_certs: False
      register: import_output

    - name: Show Export Output.
      ansible.builtin.debug:
        var: export_output

#    - name: Show Import Output.
#      ansible.builtin.debug:
#        var: import_output
