---

- name: Migrate Networking Inventory.
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

#  vars_files:
#    - /vaults/tower.yml

  tasks:
    - name: Add inventory
      ansible.controller.inventory:
        name: "Foo Inventory"
        description: "Our Foo Cloud Servers"
        organization: "Bar Org"
        state: present
        
    - name: Export inventory
      ansible.controller.export:
        inventory: 'inventory_test'
        tower_host: 10.0.109.3
        tower_username: "admin"
        tower_password: "test"
      register: export_output

#    - name: Import inventory
#      ansible.controller.import:
#        assets: "{{ export_output }}"
#        controller_host: 10.0.109.3
#        controller_username: "{{ tower_user }}"
#        controller_password: "{{ tower_pass }}"
#      register: import_output

    - name: Show Export Output.
      ansible.builtin.debug:
        var: export_output

#    - name: Show Import Output.
#      ansible.builtin.debug:
#        var: import_output
