- name: Okta
  hosts: localhost
  gather_facts: False
  tasks:  
  - name: Pull the application information from Okta
    uri:
      url: "https://dev-59865151-admin.okta.com/api/v1/apps?q=aap22_SAML"
      method: GET
      headers:
        Accept: application/json
        Content-Type: application/json
        Authorization: "SSWS 00cxrHMl6OjSc2GkZmMyK0n20P85x0QSowHS6xF7qL"

