- name: Pause Example
  hosts: localhost
  gather_facts: False
  become: False
  tasks:
    - name: Pause for 5 minutes
      ansible.builtin.pause:
        minutes: 5
    - name: Say Hello
      debug:
        msg: "Hello World!"
