- name: Read File Sample
  hosts: all
  gather_facts: False
  tasks:   
    - name: Read File
      ansible.builtin.debug:
        msg: "the value of test.txt is {{lookup('ansible.builtin.file', '/opt/tmp/test.txt') }}"
