- name: Read File Sample
  hosts: all
  gather_facts: False
  tasks:   
    - name: Read File
      ansible.builtin.debug:
        ### This file needs to be on the execution node
      # msg: "the value of test.txt is {{lookup('ansible.builtin.file', '/tmp/test.txt') }}"
        msg: "the value of test.txt is {{lookup('ansible.builtin.file', '/tmp/arcticwolf/arcticwolfagent.txt') }}"
