- name: readfile_register.yml
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Read File
      shell: >
           cat /tmp/test.txt
      register: raw_text

    - name: Display File Text
      debug:
        msg: "{{ raw_text.stdout-split('\n') }}"
