- name: role_team_assignment.yml
  hosts: localhost
  gather_facts: false

  vars:
    host: "https://10.0.109.49/"
    username: "admin"
    password: "test" 
      
  tasks:
    - name: role_team_assignment
      ansible.controller.role_team_assignment:
        controller_host: "{{ host }}"
        controller_username: "{{ username }}"
        controller_password: "{{ password }}"
        validate_certs: false
        role_definition: Controller Organization Admin
        object_id: 2
        team: Team1
        state: present
