- name: set_fact.yml
  hosts: localhost
  gather_facts: True
  use_fact_cache: True
  become: True
  tasks:   
  - name: init
    set_fact:
      one_fact: something
      one_list:
        - a
        - b
        - c

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
