- name: set_fact.yml
  hosts: localhost
  gather_facts: True
  become: True
  tasks:   
  - name: init
    set_fact:
      one_fact: something
      one_list:
        - a
        - b
        - c
      ping_data: "{{ query('ansible.controller.controller_api', 'ping') }}"

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
