- name: string_case_problem.yml
  hosts: all
  gather_facts: false
  tasks: 
    - name: Set env_name
      set_fact:
        env_name: "16"

    - name: Config tower-cli
      shell: '/var/lib/awx/venv/ansible/bin/tower-cli job launch --job-template=6 --inventory=1 --extra-vars="ENV={{env_name | string}}1" --extra-vars="appList: [ccmp]"'
