- name: string_case_problem.yml
  hosts: all
  gather_facts: false
  tasks: 
    - name: Set env_name
      set_fact:
        env_name: "16"

    - name: Config tower-cli
      shell: 'tower-cli job launch --job-template=16 --inventory=1 --insecure -h 10.0.108.52 -u admin -p test --extra-vars="ENV={{env_name | string}}" --extra-vars="appList: [ccmp]"'
