- name: Hello World Sample
  hosts: localhost
  gather_facts: False
  vars:
    machine:
      username: '{{ ansible_user }}'
      password: '{{ ansible_password }}'
  tasks:   
    - name: Print Creds
      debug:
        msg: '{{ ansible_user }}'
    - set_fact: 
        controller_password: '{{ lookup("env", "TOWER_PASSWORD") }}'
    - debug:
        msg: "{{ controller_password }}"
