- name: Hello World Sample
  hosts: localhost
  gather_facts: False
  become: True
  tasks:   
    - name: Say Hello
      debug:
        msg: "Hello World!"

    - name: Copy Files
      command: cp /apps/stealthssl/client_cert.cfg /apps/stealthShare/
