- name: test_package_module.yml
  hosts: 10.0.110.43
  gather_facts: False
  become: True
  tasks:   
#    - name: Gather the package facts
#      ansible.builtin.package_facts:
#        manager: auto

#    - name: Print the package facts
#      ansible.builtin.debug:
#        var: ansible_facts.packages

#    - name: Yum list updates
#      ansible.builtin.yum:
#        list: updates
#      register: result

#    - name: Display results
#      debug:
#        msg: "{{ result }}"
        
         
    - name: Package UPDATE AVAILABLE; state=present
      ansible.builtin.package:
        state: present
        name:
          # UPDATE AVAILABLE
          - audit-libs.x86_64
          - audit.x86_64
          - authselect-compat.x86_64
          - authselect-libs.x86_64
          - authselect.x86_64
          - bash.x86_64
          - bind-export-libs.x86_64
          - ca-certificates.noarch
          - chrony.x86_64
          - cloud-init.noarch
          - cloud-utils-growpart.noarch
          - cockpit-bridge.x86_64
          - cockpit-system.noarch
          - cockpit-ws.x86_64
          - coreutils-common.x86_64
          - coreutils.x86_64
          - cronie-anacron.x86_64
          - cronie.x86_64
          - crypto-policies-scripts.noarch
          - crypto-policies.noarch
          - cryptsetup-libs.x86_64
          - curl.x86_64
          - dbus-common.noarch
          - dbus-daemon.x86_64
          - dbus-libs.x86_64
          - dbus-tools.x86_64
          - dbus.x86_64
          - device-mapper-libs.x86_64
          - device-mapper.x86_64
          - dhcp-client.x86_64
          - dhcp-common.noarch
          - dhcp-libs.x86_64
          - dnf-data.noarch
          - dnf-plugin-subscription-manager.x86_64
          - dnf-plugins-core.noarch
          - dnf.noarch
          - dracut-config-generic.x86_64
          - dracut-network.x86_64
          - dracut-squash.x86_64
          - dracut.x86_64
          - e2fsprogs-libs.x86_64
          - e2fsprogs.x86_64
          - elfutils-debuginfod-client.x86_64
          - elfutils-default-yama-scope.noarch
          - elfutils-libelf.x86_64
          - elfutils-libs.x86_64
          - ethtool.x86_64
          - expat.x86_64
          - file-libs.x86_64
          - file.x86_64
          - freetype.x86_64
          - fuse-libs.x86_64
          - gdbm-libs.x86_64
          - gdbm.x86_64
          - gdisk.x86_64
          - glib2.x86_64
          - glibc-all-langpacks.x86_64
          - glibc-common.x86_64
          - glibc-gconv-extra.x86_64
          - glibc.x86_64
          - gnupg2-smime.x86_64
          - gnupg2.x86_64
          - gnutls.x86_64
          - grub2-common.noarch
          - grub2-efi-x64.x86_64
          - grub2-pc-modules.noarch
          - grub2-pc.x86_64
          - grub2-tools-extra.x86_64
          - grub2-tools-minimal.x86_64
          - grub2-tools.x86_64
          - grubby.x86_64
          - gssproxy.x86_64
          - gzip.x86_64
          - hwdata.noarch
          - initscripts.x86_64
          - insights-client.noarch
          - iproute.x86_64
          - iputils.x86_64
          - irqbalance.x86_64
          - kernel-core.x86_64
          - kernel-modules.x86_64
          - kernel-tools-libs.x86_64
          - kernel-tools.x86_64
          - kernel.x86_64
          - kexec-tools.x86_64
          - kpartx.x86_64
          - krb5-libs.x86_64
          - libarchive.x86_64
          - libbasicobjects.x86_64
          - libblkid.x86_64
          - libbpf.x86_64
          - libcap.x86_64
          - libcollection.x86_64
          - libcom_err.x86_64
          - libcurl.x86_64
          - libdhash.x86_64
          - libdnf.x86_64
          - libestr.x86_64
          - libfdisk.x86_64
          - libffi.x86_64
          - libgcc.x86_64
          - libgcrypt.x86_64
          - libgomp.x86_64
          - libibverbs.x86_64
          - libini_config.x86_64
          - libksba.x86_64
          - libldb.x86_64
          - libmount.x86_64
          - libnfsidmap.x86_64
          - libnl3-cli.x86_64
          - libnl3.x86_64
          - libpath_utils.x86_64
          - libpwquality.x86_64
          - libref_array.x86_64
          - librepo.x86_64
          - librhsm.x86_64
          - libselinux-utils.x86_64
          - libselinux.x86_64
          - libsemanage.x86_64
          - libsmartcols.x86_64
          - libsolv.x86_64
          - libsoup.x86_64
          - libss.x86_64
          - libssh-config.noarch
          - libssh.x86_64
          - libsss_autofs.x86_64
          - libsss_certmap.x86_64
          - libsss_idmap.x86_64
          - libsss_nss_idmap.x86_64
          - libsss_sudo.x86_64
          - libstdc++.x86_64
          - libtalloc.x86_64
          - libtasn1.x86_64
          - libtdb.x86_64
          - libteam.x86_64
          - libtevent.x86_64
          - libtirpc.x86_64
          - libuser.x86_64
          - libuuid.x86_64
          - libverto-libevent.x86_64
          - libverto.x86_64
          - libxml2.x86_64
          - linux-firmware.noarch
          - lmdb-libs.x86_64
          - logrotate.x86_64
          - memstrack.x86_64
          - microcode_ctl.x86_64
          - mokutil.x86_64
          - NetworkManager-libnm.x86_64
          - NetworkManager-team.x86_64
          - NetworkManager-tui.x86_64
          - NetworkManager.x86_64
          - nfs-utils.x86_64
          - oddjob-mkhomedir.x86_64
          - oddjob.x86_64
          - openssh-clients.x86_64
          - openssh-server.x86_64
          - openssh.x86_64
          - openssl-libs.x86_64
          - openssl-pkcs11.x86_64
          - openssl.x86_64
          - pam.x86_64
          - pciutils-libs.x86_64
          - pciutils.x86_64
          - pcre2.x86_64
          - platform-python-setuptools.noarch
          - platform-python.x86_64
          - policycoreutils-python-utils.noarch
          - policycoreutils.x86_64
          - polkit-libs.x86_64
          - polkit.x86_64
          - procps-ng.x86_64
          - python3-audit.x86_64
          - python3-cloud-what.x86_64
          - python3-dmidecode.x86_64
          - python3-dnf-plugins-core.noarch
          - python3-dnf.noarch
          - python3-hawkey.x86_64
          - python3-libdnf.x86_64
          - python3-librepo.x86_64
          - python3-libs.x86_64
          - python3-libselinux.x86_64
          - python3-libsemanage.x86_64
          - python3-libxml2.x86_64
          - python3-linux-procfs.noarch
          - python3-magic.noarch
          - python3-perf.x86_64
          - python3-policycoreutils.noarch
          - python3-rpm.x86_64
          - python3-setuptools-wheel.noarch
          - python3-subscription-manager-rhsm.x86_64
          - python3-syspurpose.x86_64
          - python3-unbound.x86_64
          - qemu-guest-agent.x86_64
          - redhat-release-eula.x86_64
          - redhat-release.x86_64
          - rhc.x86_64
          - rhsm-icons.noarch
          - rpcbind.x86_64
          - rpm-build-libs.x86_64
          - rpm-libs.x86_64
          - rpm-plugin-selinux.x86_64
          - rpm-plugin-systemd-inhibit.x86_64
          - rpm.x86_64
          - rsync.x86_64
          - rsyslog.x86_64
          - selinux-policy-targeted.noarch
          - selinux-policy.noarch
          - setroubleshoot-server.x86_64
          - setup.noarch
          - sg3_utils-libs.x86_64
          - sg3_utils.x86_64
          - shadow-utils.x86_64
          - shim-x64.x86_64
          - sos.noarch
          - sqlite-libs.x86_64
          - sscg.x86_64
          - sssd-client.x86_64
          - sssd-common.x86_64
          - sssd-kcm.x86_64
          - sssd-nfs-idmap.x86_64
          - subscription-manager-cockpit.noarch
          - subscription-manager-rhsm-certificates.x86_64
          - subscription-manager.x86_64
          - sudo.x86_64
          - systemd-libs.x86_64
          - systemd-pam.x86_64
          - systemd-udev.x86_64
          - systemd.x86_64
          - tar.x86_64
          - teamd.x86_64
          - tuned.noarch
          - tzdata.noarch
          - unbound-libs.x86_64
          - util-linux.x86_64
          - vim-minimal.x86_64
          - virt-what.x86_64
          - which.x86_64
          - xz-libs.x86_64
          - xz.x86_64
          - yum-utils.noarch
          - yum.noarch
          - zlib.x86_64
          
    - name: Package NO UPDATE AVAILABLE; state=present
      ansible.builtin.package:
        state: present
        name:
          #NO UPDATE AVAILABLE
          - abattis-cantarell-fonts.noarch
          - acl.x86_64
          - basesystem.noarch
          - brotli.x86_64
          - bzip2-libs.x86_64
          - bzip2.x86_64
          - c-ares.x86_64
          - cairo-gobject.x86_64
          - cairo.x86_64
          - checkpolicy.x86_64
          - chkconfig.x86_64
          - cpio.x86_64
          - cracklib-dicts.x86_64
          - cracklib.x86_64
          - crontabs.noarch
          - cyrus-sasl-lib.x86_64
          - dbus-glib.x86_64
          - dbxtool.x86_64
          - dejavu-fonts-common.noarch
          - dejavu-sans-mono-fonts.noarch
          - diffutils.x86_64
          - dmidecode.x86_64
          - dosfstools.x86_64
          - efi-filesystem.noarch
          - efibootmgr.x86_64
          - efivar-libs.x86_64
          - efivar.x86_64
          - filesystem.x86_64
          - findutils.x86_64
          - fontconfig.x86_64
          - fontpackages-filesystem.noarch
          - gawk.x86_64
          - gdk-pixbuf2.x86_64
          - geolite2-city.noarch
          - geolite2-country.noarch
          - gettext-libs.x86_64
          - gettext.x86_64
          - glib-networking.x86_64
          - gmp.x86_64
          - gobject-introspection.x86_64
          - gpgme.x86_64
          - grep.x86_64
          - groff-base.x86_64
          - gsettings-desktop-schemas.x86_64
          - hardlink.x86_64
          - hdparm.x86_64
          - hostname.x86_64
          - ima-evm-utils.x86_64
          - info.x86_64
          - ipcalc.x86_64
          - jansson.x86_64
          - json-c.x86_64
          - json-glib.x86_64
          - kbd-legacy.noarch
          - kbd-misc.noarch
          - kbd.x86_64
          - keyutils-libs.x86_64
          - keyutils.x86_64
          - kmod-libs.x86_64
          - kmod.x86_64
          - less.x86_64
          - libacl.x86_64
          - libappstream-glib.x86_64
          - libassuan.x86_64
          - libattr.x86_64
          - libcap-ng.x86_64
          - libcomps.x86_64
          - libcroco.x86_64
          - libdaemon.x86_64
          - libdb-utils.x86_64
          - libdb.x86_64
          - libedit.x86_64
          - libevent.x86_64
          - libfastjson.x86_64
          - libgpg-error.x86_64
          - libidn2.x86_64
          - libkcapi-hmaccalc.x86_64
          - libkcapi.x86_64
          - libmaxminddb.x86_64
          - libmnl.x86_64
          - libmodman.x86_64
          - libmodulemd.x86_64
          - libndp.x86_64
          - libnghttp2.x86_64
          - libnsl2.x86_64
          - libpcap.x86_64
          - libpipeline.x86_64
          - libpkgconf.x86_64
          - libpng.x86_64
          - libproxy.x86_64
          - libpsl.x86_64
          - libreport-filesystem.x86_64
          - libseccomp.x86_64
          - libsecret.x86_64
          - libsepol.x86_64
          - libsigsegv.x86_64
          - libstemmer.x86_64
          - libsysfs.x86_64
          - libunistring.x86_64
          - libusbx.x86_64
          - libutempter.x86_64
          - libX11-common.noarch
          - libX11.x86_64
          - libXau.x86_64
          - libxcb.x86_64
          - libxcrypt.x86_64
          - libXext.x86_64
          - libxkbcommon.x86_64
          - libXrender.x86_64
          - libyaml.x86_64
          - libzstd.x86_64
          - lshw.x86_64
          - lsscsi.x86_64
          - lua-libs.x86_64
          - lz4-libs.x86_64
          - lzo.x86_64
          - man-db.x86_64
          - mozjs60.x86_64
          - mpfr.x86_64
          - ncurses-base.noarch
          - ncurses-libs.x86_64
          - ncurses.x86_64
          - net-tools.x86_64
          - nettle.x86_64
          - newt.x86_64
          - npth.x86_64
          - numactl-libs.x86_64
          - openldap.x86_64
          - os-prober.x86_64
          - p11-kit-trust.x86_64
          - p11-kit.x86_64
          - PackageKit-glib.x86_64
          - PackageKit.x86_64
          - parted.x86_64
          - passwd.x86_64
          - pcre.x86_64
          - pigz.x86_64
          - pinentry.x86_64
          - pixman.x86_64
          - pkgconf-m4.noarch
          - pkgconf-pkg-config.x86_64
          - pkgconf.x86_64
          - platform-python-pip.noarch
          - polkit-pkla-compat.x86_64
          - popt.x86_64
          - prefixdevname.x86_64
          - psmisc.x86_64
          - publicsuffix-list-dafsa.noarch
          - python3-babel.noarch
          - python3-cairo.x86_64
          - python3-cffi.x86_64
          - python3-chardet.noarch
          - python3-configobj.noarch
          - python3-cryptography.x86_64
          - python3-dateutil.noarch
          - python3-dbus.x86_64
          - python3-decorator.noarch
          - python3-ethtool.x86_64
          - python3-gobject-base.x86_64
          - python3-gobject.x86_64
          - python3-gpg.x86_64
          - python3-idna.noarch
          - python3-iniparse.noarch
          - python3-inotify.noarch
          - python3-jinja2.noarch
          - python3-jsonpatch.noarch
          - python3-jsonpointer.noarch
          - python3-jsonschema.noarch
          - python3-jwt.noarch
          - python3-libcomps.x86_64
          - python3-markupsafe.x86_64
          - python3-netifaces.x86_64
          - python3-oauthlib.noarch
          - python3-pexpect.noarch
          - python3-pip-wheel.noarch
          - python3-ply.noarch
          - python3-prettytable.noarch
          - python3-ptyprocess.noarch
          - python3-pycparser.noarch
          - python3-pydbus.noarch
          - python3-pyserial.noarch
          - python3-pysocks.noarch
          - python3-pytz.noarch
          - python3-pyudev.noarch
          - python3-pyyaml.x86_64
          - python3-requests.noarch
          - python3-setools.x86_64
          - python3-six.noarch
          - python3-systemd.x86_64
          - python3-urllib3.noarch
          - quota-nls.noarch
          - quota.x86_64
          - readline.x86_64
          - redhat-logos.x86_64
          - rootfiles.noarch
          - sed.x86_64
          - setroubleshoot-plugins.noarch
          - shared-mime-info.x86_64
          - slang.x86_64
          - snappy.x86_64
          - squashfs-tools.x86_64
          - tcpdump.x86_64
          - timedatex.x86_64
          - tpm2-tss.x86_64
          - trousers-lib.x86_64
          - trousers.x86_64
          - usermode.x86_64
          - xfsprogs.x86_64
          - xkeyboard-config.noarch
          
    - name: Package NOT INSTALLED; state=present
      ansible.builtin.package:
        state: present
        name:
          # NOT INSTALLED
          - aajohan-comfortaa-fonts.noarch
          - aardvark-dns.x86_64          
          - java-1.8.0-openjdk 
          - asciidoc.noarch
          - aspell-en.x86_64
          - aspell.i686
          - aspell.x86_64
          - bzip2-devel.i686
          - bzip2-devel.x86_64
          - bzip2-libs.i686
          - c-ares-devel.i686
          - c-ares-devel.x86_64
          - c-ares.i686
          - c2esp.x86_64
          - cachefilesd.x86_64
          - cairo-devel.i686
          - cairo-devel.x86_64
          - cairo-gobject-devel.i686
          - cairo-gobject-devel.x86_64
          - cairo-gobject.i686
          - cairo.i686
          - cairomm.i686
          - cairomm.x86_64
          - cargo-doc.noarch
          - cargo-vendor.x86_64
          - cargo.x86_64
          - cdi-api.noarch
          - cdparanoia-libs.i686
          - cdparanoia-libs.x86_64
          - cdparanoia.x86_64
          - cdrdao.x86_64
          - celt051.i686
          - celt051.x86_64
          - certmonger.x86_64
          - cgdcbxd.x86_64
          - chan.i686
          - chan.x86_64
          - check-devel.i686
          - check-devel.x86_64
          - check.i686
          - check.x86_64
          - cheese-libs.i686
          - cheese-libs.x86_64
          - cheese.x86_64
          - chrome-gnome-shell.x86_64
          - chrpath.x86_64
          - cifs-utils.x86_64
          - cim-schema.noarch
          - cjose-devel.x86_64
          - cjose.x86_64
          - clang-analyzer.noarch
          - clang-devel.i686
          - clang-devel.x86_64
          - clang-libs.i686
          - clang-libs.x86_64
          - clang-resource-filesystem.i686
          - clang-resource-filesystem.x86_64
          - clang-tools-extra.i686
          - clang-tools-extra.x86_64
          - clang.i686
          - clang.x86_64
          - cldr-emoji-annotation.noarch
          - clevis-dracut.x86_64
          - clevis-luks.x86_64
          - clevis-systemd.x86_64
          - clevis-udisks2.x86_64
          - clevis.x86_64
          - clippy.x86_64
          - clucene-contribs-lib.i686
          - clucene-contribs-lib.x86_64
          - clucene-core.i686
          - clucene-core.x86_64
          - clutter-gst2.i686
          - clutter-gst2.x86_64
          - clutter-gst3.i686
          - clutter-gst3.x86_64
          - clutter-gtk.i686
          - clutter-gtk.x86_64
          - clutter.i686
          - clutter.x86_64
          - cmake-data.noarch
          - cmake-doc.noarch
          - cmake-filesystem.i686
          - cmake-filesystem.x86_64
          - cmake-gui.x86_64
          - cmake-rpm-macros.noarch
          - cmake.x86_64
          - cockpit-composer.noarch
          - cockpit-dashboard.noarch
          - cockpit-doc.noarch
          - cockpit-leapp.noarch
          - cockpit-machines.noarch
          - cockpit-packagekit.noarch
          - cockpit-pcp.x86_64
          - cockpit-podman.noarch
          - cockpit-session-recording.noarch
          - cockpit-storaged.noarch
          - cockpit.x86_64
          - cogl.i686
          - cogl.x86_64
          - color-filesystem.noarch
          - colord-gtk.i686
          - colord-gtk.x86_64
          - colord-libs.i686
          - colord-libs.x86_64
          - colord.x86_64
          - compat-exiv2-026.i686
          - compat-exiv2-026.x86_64
          - compat-hwloc1.i686
          - compat-hwloc1.x86_64
          - compat-libgfortran-48.i686
          - compat-libgfortran-48.x86_64
          - compat-libpthread-nonshared.x86_64
          - compat-libtiff3.i686
          - compat-libtiff3.x86_64
          - compat-openssl10.i686
          - compat-openssl10.x86_64
          - compiler-rt.i686
          - compiler-rt.x86_64
          - composer-cli.x86_64          

#    - name: Yum list updates
#      ansible.builtin.yum:
#        list: updates
#      register: result2

#    - name: Display results
#      debug:
#        msg: "{{ result2 }}"
