- name: Testing
  hosts: localhost
  gather_facts: False
  vars:
    machine:
      username: '{{ ansible_user }}'
      password: '{{ ansible_password }}'
    controller:
      host: '{{ lookup("env", "CONTROLLER_HOST") }}'
      username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
      password: '{{ lookup("env", "CONTROLLER_PASSWORD") }}'
  tasks:   
    - name: Print Machine Creds
      debug:
        msg: "Username: {{ ansible_user }}, Password: {{ ansible_password }}"
    - name: Print Tower Creds
      debug:
        msg: "host: {{ controller.host }}, username: {{ controller.username }}, password: {{ controller.password }}"
