- name: Testing
  hosts: localhost
  gather_facts: False
  vars:
    tower:
      host: '{{ lookup("env", "TOWER_HOST") }}'
      username: '{{ lookup("env", "TOWER_USERNAME") }}'
      password: '{{ lookup("env", "TOWER_PASSWORD") }}'
  tasks:   
    - name: Print Machine Creds
      debug:
        msg: "Username: {{ ansible_user }}, Password: {{ ansible_password }}"
    - name: Print Tower Creds
      debug:
        msg: "host: {{ tower.host }}, username: {{ tower.username }}, password: {{ tower.password }}"
