- name: Testing
  hosts: localhost
  gather_facts: True
  vars:
    tower:
      host: '{{ lookup("env", "TOWER_HOST") }}'
      username: '{{ lookup("env", "TOWER_USERNAME") }}'
      password: '{{ lookup("env", "TOWER_PASSWORD") }}'
  tasks:   
    - name: Print Creds
      debug:
        msg: "Username: {{ ansible_user }}, Password: {{ ansible_password }}"
    - name: print tower stuff
      debug:
        msg: "host: {{ tower.host }}"
        #, username: {{ username }}, password: {{ password }}"
