- name: test_package_module.yml
  hosts: all
  gather_facts: False
  become: False
  tasks:   
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Print the package facts
      ansible.builtin.debug:
        var: ansible_facts.packages

    - name: Yum list updates
      ansible.builtin.yum:
        list: updates
      register: result

    - name: Display users
      debug:
        msg: result
