- name: test_package_module.yml
  hosts: jbird-rhel8
  gather_facts: False
  become: True
  tasks:   
#    - name: Gather the package facts
#      ansible.builtin.package_facts:
#        manager: auto

#    - name: Print the package facts
#      ansible.builtin.debug:
#        var: ansible_facts.packages

    - name: Yum list updates
      ansible.builtin.yum:
        list: updates
      register: result

    - name: Display results
      debug:
        msg: "{{ result }}"
        
    - name: Package state=present
      ansible.builtin.package:
        name:
          - sos.noarch
          - yum.noarch
          - rsyslog.x86_64
          - ansible
        state: present

    - name: Yum list updates
      ansible.builtin.yum:
        list: updates
      register: result2

    - name: Display results
      debug:
        msg: "{{ result2 }}"
