- name: Hello World Sample
  hosts: localhost
  gather_facts: False
  #become: True
  tasks:   
    - name: Say Hello
      debug:
        msg: "Hello World!"

   # - name: Copy cert.cfg to Client
      #copy:  
       # src: /apps/stealthssl/client_cert.cfg
       # dest: /stealthShare/
       # mode: 0755

    - name: Generate Private Key
      command:cp /apps/stealthssl/client_cert.cfg /apps/stealthShare/

    - name: Delete Old Signing Request
      shell: "rm -rf /opt/*.csr"

    - name: Generate CSR
      command: 'openssl req -new -key {{ ansible_hostname }}.key -subj "/C=US/ST=MD/L=Aberdeen/O=AFC/OU=C5ISR/CN={{ csr_cn }}.c3sys.army.mil" -passin pass:{{ password_var }} -out {{ ansible_hostname }}.csr'
      args:
        chdir: /opt/
