- name: oauthtoken
  hosts: localhost
  gather_facts: False
  tasks:   
    - name: Delete Inventories
      tower_inventory:
        name: test_inv_1
        organization: Default
        state: absent
        validate_certs: no
