- name: Update AAP Credential Object
  hosts: all 
  vars:
    ansible_url: 10.0.110.232
    credobj_id: 12
    aap_user: admin
    aap_password: test
    service_AccountAD: test1
    passwordFetched: test1
    
  tasks: 
    - name: Update Ansible Credential Object 
      ansible.builtin.uri:
            url: https://{{ ansible_url }}/api/v2/credentials/{{ credobj_id }}/
            user: "{{aap_user}}"
            password: "{{aap_password}}"
            method: PATCH
            body:
              inputs:
                username: "{{service_AccountAD}}"
                password: "{{passwordFetched}}"
            body_format: json
            force_basic_auth: true
            status_code: 200
            validate_certs: no
      register: result
      #delegate_to: localhost
