- name: upload_license.yml
  hosts: localhost
  gather_facts: false

  vars:
    #host: "https://10.0.109.139/"
    #host: "https://10.0.111.182/"
    host: "https://10.0.108.230/"
    username: "admin"
    password: "test" 
    
  tasks:   
    - name: Set the license using a file
      ansible.controller.license:
        manifest: "test.zip"
        controller_host: "{{ host }}"
        controller_username: "{{ username }}"
        controller_password: "{{ password }}"
        validate_certs: false

