- name: uri_test.yml
  hosts: all
  gather_facts: True
  become: True
  tasks:  
  - name: Create a JIRA issue
    ansible.builtin.uri:
      url: https://10.0.108.52/api/v2/login
      user: admin
      password: test
      method: GET
      body:
        Username: admin
        Password: test
      #force_basic_auth: true
      status_code: 200
      body_format: json
     # validate_certs: false
    
