- name: vmware.vmware_rest.vm_moid.yml
  hosts: localhost
  gather_facts: False
  become: False
  tasks:   
  - name: set connection info
    ansible.builtin.set_fact:
      connection_args:
        vcenter_hostname: "vcenter.test"
        vcenter_username: "administrator@vsphere.local"
        vcenter_password: "1234"

  - name: lookup MoID of the object
    ansible.builtin.debug: msg="{{ lookup('vmware.vmware_rest.vm_moid', '/my_dc/host/my_cluster/esxi1.test/test_vm1', **connection_args) }}"

  - name: lookup MoID of the object inside the path
    ansible.builtin.debug: msg="{{ lookup('vmware.vmware_rest.vm_moid', '/my_dc/vm/') }}"
