- name: Windows
  hosts: windows
  gather_facts: false
  tasks:   
    - name: "Delete the old installation log"
      become_method: runas
      become_user: ansible_user
      become: true
      ansible.windows.win_file:
        path: C:\Becnet\Ansible\powershell7.log
        state: absent

    - name: "PowerShell 7.2.4 is installed"
      become_method: runas
      become_user: ansible_user
      become: true
      ansible.windows.win_package:
        #path: \\mds-bechtel\serversoft\GIO-jumpbox\PowerShell-7.2.4-win-x64.msi
        path: https://github.com/PowerShell/PowerShell/releases/download/v7.2.4/PowerShell-7.2.4-win-x64.msi
        product_id: '{5111A64F-53EF-4C44-AA6B-327CA6826887}'
        state: present
        log_path: C:\Becnet\Ansible\powershell7.log
        arguments:
          - ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=1
          - ENABLE_PSREMOTING=1
          - REGISTER_MANIFEST=1
          - USE_MU=0
          - ENABLE_MU=0
