- name: win_powershell_hello_world.yml
  hosts: all
  gather_facts: false
  tasks:
    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
        script: |
          echo "Hello World"
