- name: Workflow OS Test A
  hosts: localhost
  gather_facts: False
  become: False
  tasks:   
    - name: Check if OS = "A"
      debug:
        msg: "{{ OS }}"
    - name: Do stuff based on OS
      debug:
        msg: "Im doing OS A stuff"
      when: {{ OS }} == "A"
