- name: Workflow OS Test A
  hosts: localhost
  gather_facts: False
  become: False
  tasks:   
    - ansible.builtin.assert: { that: "OS == 'A'" }
    - name: What is OS
      debug:
        msg: "OS is = {{ OS }}"
    - name: Dont do stuff if OS is NOT A
      debug:
        msg: "Im not doing stuff because the OS is {{ OS }}"
      when: OS != "A"       
    - name: Do stuff if OS is A
      debug:
        msg: "Im doing stuff because the OS is A"
      when: OS == "A"
