- name: Hello World Sample
  hosts: all
  gather_facts: False
  tasks:   
    - name: Say Hello
      uri:
        url: https://3.15.223.215/api/v2/job_template/7/launch
        body_format: json
        headers:
          authorization: bearer <token>
        method: "POST"
        status_code: 201
