- name: Yo Dawg
  hosts: all
  gather_facts: False
  tasks:   
    - name: I heard you like api calls
      uri:
        url: https://10.42.0.42/api/v2/job_templates/10/launch/
        validate_certs: false
        headers:
          authorization: bearer FXLSLcgNT4xOfAd3ZHnyUXIw1cx4NA
        method: POST
        status_code: 201
