- name: Yo Dawg
  hosts: all
  gather_facts: False
  tasks:   
    - name: Say Hello
      uri:
        url: https://10.42.0.42/api/v2/job_templates/10/launch/
        validate_certs: false
        method: POST
        status_code: 201
